# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddRoleInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import RoleMstOutputProto_pb2 as RoleMstOutputProto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AddRoleInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x41\x64\x64RoleInputProto.proto\x1a\x18RoleMstOutputProto.proto\"f\n\x11\x41\x64\x64RoleInputProto\x12\x0f\n\x07userUID\x18\x01 \x01(\t\x12\x1c\n\x14searchOrganizationID\x18\x02 \x01(\t\x12\"\n\x05right\x18\x03 \x03(\x0b\x32\x13.RoleMstOutputProtoB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
  ,
  dependencies=[RoleMstOutputProto__pb2.DESCRIPTOR,])




_ADDROLEINPUTPROTO = _descriptor.Descriptor(
  name='AddRoleInputProto',
  full_name='AddRoleInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userUID', full_name='AddRoleInputProto.userUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchOrganizationID', full_name='AddRoleInputProto.searchOrganizationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right', full_name='AddRoleInputProto.right', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=155,
)

_ADDROLEINPUTPROTO.fields_by_name['right'].message_type = RoleMstOutputProto__pb2._ROLEMSTOUTPUTPROTO
DESCRIPTOR.message_types_by_name['AddRoleInputProto'] = _ADDROLEINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRoleInputProto = _reflection.GeneratedProtocolMessageType('AddRoleInputProto', (_message.Message,), {
  'DESCRIPTOR' : _ADDROLEINPUTPROTO,
  '__module__' : 'AddRoleInputProto_pb2'
  # @@protoc_insertion_point(class_scope:AddRoleInputProto)
  })
_sym_db.RegisterMessage(AddRoleInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
