# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AdminChangePasswordInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AdminChangePasswordInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#AdminChangePasswordInputProto.proto\"r\n\x1d\x41\x64minChangePasswordInputProto\x12\x0f\n\x07userUID\x18\x01 \x01(\t\x12\x13\n\x0boldPassword\x18\x02 \x01(\t\x12\x13\n\x0bnewPassword\x18\x03 \x01(\t\x12\x16\n\x0e\x63ofirmPassword\x18\x04 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_ADMINCHANGEPASSWORDINPUTPROTO = _descriptor.Descriptor(
  name='AdminChangePasswordInputProto',
  full_name='AdminChangePasswordInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userUID', full_name='AdminChangePasswordInputProto.userUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='oldPassword', full_name='AdminChangePasswordInputProto.oldPassword', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newPassword', full_name='AdminChangePasswordInputProto.newPassword', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cofirmPassword', full_name='AdminChangePasswordInputProto.cofirmPassword', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=153,
)

DESCRIPTOR.message_types_by_name['AdminChangePasswordInputProto'] = _ADMINCHANGEPASSWORDINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdminChangePasswordInputProto = _reflection.GeneratedProtocolMessageType('AdminChangePasswordInputProto', (_message.Message,), {
  'DESCRIPTOR' : _ADMINCHANGEPASSWORDINPUTPROTO,
  '__module__' : 'AdminChangePasswordInputProto_pb2'
  # @@protoc_insertion_point(class_scope:AdminChangePasswordInputProto)
  })
_sym_db.RegisterMessage(AdminChangePasswordInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
