# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BasicFormProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BasicFormProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x42\x61sicFormProto.proto\"\xae\x01\n\x0fPluginInfoProto\x12\x11\n\tpluginUID\x18\x01 \x01(\t\x12\x12\n\npluginName\x18\x02 \x01(\t\x12\x0f\n\x07\x64llName\x18\x03 \x01(\t\x12\x11\n\tclassName\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x12\n\npluginType\x18\x06 \x01(\t\x12\'\n\x0e\x42\x61sicFormProto\x18\x07 \x03(\x0b\x32\x0f.BasicFormProto\"\x97\x01\n\x0e\x42\x61sicFormProto\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0c\n\x04prop\x18\x03 \x01(\t\x12\x19\n\x03opt\x18\x04 \x03(\x0b\x32\x0c.OptionProto\x12\x10\n\x08linkFlag\x18\x05 \x01(\t\x12\x18\n\x10\x66ieldDescription\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61taDefault\x18\x07 \x01(\t\"\x96\x01\n\x12PluginInfoDtoProto\x12\x12\n\nserviceUID\x18\x01 \x01(\t\x12\x11\n\tpluginUID\x18\x02 \x01(\t\x12\x10\n\x08ifEnable\x18\x03 \x01(\x08\x12\x12\n\npluginName\x18\x04 \x01(\t\x12\x33\n\x14\x42\x61sicFormConfigProto\x18\x05 \x03(\x0b\x32\x15.BasicFormConfigProto\"\xaf\x01\n\x15PluginInfoDtoMstProto\x12\x12\n\nserviceUID\x18\x01 \x01(\t\x12\x11\n\tpluginUID\x18\x02 \x01(\t\x12\x10\n\x08ifEnable\x18\x03 \x01(\x08\x12\x12\n\npluginName\x18\x04 \x01(\t\x12\x14\n\x0ctriggerTimes\x18\x05 \x01(\t\x12\x33\n\x14\x42\x61sicFormConfigProto\x18\x06 \x03(\x0b\x32\x15.BasicFormConfigProto\"\xaf\x01\n\x14\x42\x61sicFormConfigProto\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0c\n\x04prop\x18\x03 \x01(\t\x12\x19\n\x03opt\x18\x04 \x03(\x0b\x32\x0c.OptionProto\x12\x10\n\x08linkFlag\x18\x05 \x01(\t\x12\x18\n\x10\x66ieldDescription\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\t\x12\x17\n\x0fpluginConfigUID\x18\x08 \x01(\t\"*\n\x0bOptionProto\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04prop\x18\x02 \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
)




_PLUGININFOPROTO = _descriptor.Descriptor(
  name='PluginInfoProto',
  full_name='PluginInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pluginUID', full_name='PluginInfoProto.pluginUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginName', full_name='PluginInfoProto.pluginName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dllName', full_name='PluginInfoProto.dllName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='className', full_name='PluginInfoProto.className', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='PluginInfoProto.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginType', full_name='PluginInfoProto.pluginType', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BasicFormProto', full_name='PluginInfoProto.BasicFormProto', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=199,
)


_BASICFORMPROTO = _descriptor.Descriptor(
  name='BasicFormProto',
  full_name='BasicFormProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='BasicFormProto.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='BasicFormProto.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop', full_name='BasicFormProto.prop', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt', full_name='BasicFormProto.opt', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linkFlag', full_name='BasicFormProto.linkFlag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fieldDescription', full_name='BasicFormProto.fieldDescription', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataDefault', full_name='BasicFormProto.dataDefault', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=353,
)


_PLUGININFODTOPROTO = _descriptor.Descriptor(
  name='PluginInfoDtoProto',
  full_name='PluginInfoDtoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serviceUID', full_name='PluginInfoDtoProto.serviceUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginUID', full_name='PluginInfoDtoProto.pluginUID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ifEnable', full_name='PluginInfoDtoProto.ifEnable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginName', full_name='PluginInfoDtoProto.pluginName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BasicFormConfigProto', full_name='PluginInfoDtoProto.BasicFormConfigProto', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=506,
)


_PLUGININFODTOMSTPROTO = _descriptor.Descriptor(
  name='PluginInfoDtoMstProto',
  full_name='PluginInfoDtoMstProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serviceUID', full_name='PluginInfoDtoMstProto.serviceUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginUID', full_name='PluginInfoDtoMstProto.pluginUID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ifEnable', full_name='PluginInfoDtoMstProto.ifEnable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginName', full_name='PluginInfoDtoMstProto.pluginName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='triggerTimes', full_name='PluginInfoDtoMstProto.triggerTimes', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BasicFormConfigProto', full_name='PluginInfoDtoMstProto.BasicFormConfigProto', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=684,
)


_BASICFORMCONFIGPROTO = _descriptor.Descriptor(
  name='BasicFormConfigProto',
  full_name='BasicFormConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='BasicFormConfigProto.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='BasicFormConfigProto.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop', full_name='BasicFormConfigProto.prop', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opt', full_name='BasicFormConfigProto.opt', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linkFlag', full_name='BasicFormConfigProto.linkFlag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fieldDescription', full_name='BasicFormConfigProto.fieldDescription', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='BasicFormConfigProto.data', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pluginConfigUID', full_name='BasicFormConfigProto.pluginConfigUID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=687,
  serialized_end=862,
)


_OPTIONPROTO = _descriptor.Descriptor(
  name='OptionProto',
  full_name='OptionProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='OptionProto.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prop', full_name='OptionProto.prop', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=864,
  serialized_end=906,
)

_PLUGININFOPROTO.fields_by_name['BasicFormProto'].message_type = _BASICFORMPROTO
_BASICFORMPROTO.fields_by_name['opt'].message_type = _OPTIONPROTO
_PLUGININFODTOPROTO.fields_by_name['BasicFormConfigProto'].message_type = _BASICFORMCONFIGPROTO
_PLUGININFODTOMSTPROTO.fields_by_name['BasicFormConfigProto'].message_type = _BASICFORMCONFIGPROTO
_BASICFORMCONFIGPROTO.fields_by_name['opt'].message_type = _OPTIONPROTO
DESCRIPTOR.message_types_by_name['PluginInfoProto'] = _PLUGININFOPROTO
DESCRIPTOR.message_types_by_name['BasicFormProto'] = _BASICFORMPROTO
DESCRIPTOR.message_types_by_name['PluginInfoDtoProto'] = _PLUGININFODTOPROTO
DESCRIPTOR.message_types_by_name['PluginInfoDtoMstProto'] = _PLUGININFODTOMSTPROTO
DESCRIPTOR.message_types_by_name['BasicFormConfigProto'] = _BASICFORMCONFIGPROTO
DESCRIPTOR.message_types_by_name['OptionProto'] = _OPTIONPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PluginInfoProto = _reflection.GeneratedProtocolMessageType('PluginInfoProto', (_message.Message,), {
  'DESCRIPTOR' : _PLUGININFOPROTO,
  '__module__' : 'BasicFormProto_pb2'
  # @@protoc_insertion_point(class_scope:PluginInfoProto)
  })
_sym_db.RegisterMessage(PluginInfoProto)

BasicFormProto = _reflection.GeneratedProtocolMessageType('BasicFormProto', (_message.Message,), {
  'DESCRIPTOR' : _BASICFORMPROTO,
  '__module__' : 'BasicFormProto_pb2'
  # @@protoc_insertion_point(class_scope:BasicFormProto)
  })
_sym_db.RegisterMessage(BasicFormProto)

PluginInfoDtoProto = _reflection.GeneratedProtocolMessageType('PluginInfoDtoProto', (_message.Message,), {
  'DESCRIPTOR' : _PLUGININFODTOPROTO,
  '__module__' : 'BasicFormProto_pb2'
  # @@protoc_insertion_point(class_scope:PluginInfoDtoProto)
  })
_sym_db.RegisterMessage(PluginInfoDtoProto)

PluginInfoDtoMstProto = _reflection.GeneratedProtocolMessageType('PluginInfoDtoMstProto', (_message.Message,), {
  'DESCRIPTOR' : _PLUGININFODTOMSTPROTO,
  '__module__' : 'BasicFormProto_pb2'
  # @@protoc_insertion_point(class_scope:PluginInfoDtoMstProto)
  })
_sym_db.RegisterMessage(PluginInfoDtoMstProto)

BasicFormConfigProto = _reflection.GeneratedProtocolMessageType('BasicFormConfigProto', (_message.Message,), {
  'DESCRIPTOR' : _BASICFORMCONFIGPROTO,
  '__module__' : 'BasicFormProto_pb2'
  # @@protoc_insertion_point(class_scope:BasicFormConfigProto)
  })
_sym_db.RegisterMessage(BasicFormConfigProto)

OptionProto = _reflection.GeneratedProtocolMessageType('OptionProto', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONPROTO,
  '__module__' : 'BasicFormProto_pb2'
  # @@protoc_insertion_point(class_scope:OptionProto)
  })
_sym_db.RegisterMessage(OptionProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
