# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DicTypeMstProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DicTypeMstProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x44icTypeMstProto.proto\"\xc7\x06\n\x0f\x44icTypeMstProto\x12\x10\n\x08typeCode\x18\x01 \x01(\t\x12\x10\n\x08typeName\x18\x02 \x01(\t\x12\x12\n\ncodeScheme\x18\x03 \x01(\t\x12\x11\n\ttypeClass\x18\x04 \x01(\t\x12\x17\n\x0f\x61llowCreateItem\x18\x05 \x01(\t\x12\x17\n\x0f\x61llowUpdateItem\x18\x06 \x01(\t\x12\x17\n\x0f\x61llowDeleteItem\x18\x07 \x01(\t\x12\x0c\n\x04memo\x18\x08 \x01(\t\x12\x19\n\x11itemRepresenTitle\x18\t \x01(\t\x12\x1d\n\x15itemRepresenExt1Title\x18\n \x01(\t\x12\x1d\n\x15itemRepresenExt2Title\x18\x0b \x01(\t\x12\x1d\n\x15itemRepresenExt3Title\x18\x0c \x01(\t\x12\x1d\n\x15itemRepresenExt4Title\x18\r \x01(\t\x12\x1d\n\x15itemRepresenExt5Title\x18\x0e \x01(\t\x12\x1d\n\x15itemRepresenExt6Title\x18\x0f \x01(\t\x12\x1d\n\x15itemRepresenExt7Title\x18\x10 \x01(\t\x12\x1d\n\x15itemRepresenExt8Title\x18\x11 \x01(\t\x12\x1d\n\x15itemRepresenExt9Title\x18\x12 \x01(\t\x12\x1e\n\x16itemRepresenExt10Title\x18\x13 \x01(\t\x12\x1e\n\x16itemRepresenExt11Title\x18\x14 \x01(\t\x12\x1e\n\x16itemRepresenExt12Title\x18\x15 \x01(\t\x12\x1e\n\x16itemRepresenExt13Title\x18\x16 \x01(\t\x12\x1e\n\x16itemRepresenExt14Title\x18\x17 \x01(\t\x12\x1e\n\x16itemRepresenExt15Title\x18\x18 \x01(\t\x12\x1e\n\x16itemRepresenExt16Title\x18\x19 \x01(\t\x12\x1e\n\x16itemRepresenExt17Title\x18\x1a \x01(\t\x12\x1e\n\x16itemRepresenExt18Title\x18\x1b \x01(\t\x12\x1e\n\x16itemRepresenExt19Title\x18\x1c \x01(\t\x12\x1e\n\x16itemRepresenExt20Title\x18\x1d \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_DICTYPEMSTPROTO = _descriptor.Descriptor(
  name='DicTypeMstProto',
  full_name='DicTypeMstProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeCode', full_name='DicTypeMstProto.typeCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typeName', full_name='DicTypeMstProto.typeName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codeScheme', full_name='DicTypeMstProto.codeScheme', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typeClass', full_name='DicTypeMstProto.typeClass', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allowCreateItem', full_name='DicTypeMstProto.allowCreateItem', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allowUpdateItem', full_name='DicTypeMstProto.allowUpdateItem', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allowDeleteItem', full_name='DicTypeMstProto.allowDeleteItem', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memo', full_name='DicTypeMstProto.memo', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenTitle', full_name='DicTypeMstProto.itemRepresenTitle', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt1Title', full_name='DicTypeMstProto.itemRepresenExt1Title', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt2Title', full_name='DicTypeMstProto.itemRepresenExt2Title', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt3Title', full_name='DicTypeMstProto.itemRepresenExt3Title', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt4Title', full_name='DicTypeMstProto.itemRepresenExt4Title', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt5Title', full_name='DicTypeMstProto.itemRepresenExt5Title', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt6Title', full_name='DicTypeMstProto.itemRepresenExt6Title', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt7Title', full_name='DicTypeMstProto.itemRepresenExt7Title', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt8Title', full_name='DicTypeMstProto.itemRepresenExt8Title', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt9Title', full_name='DicTypeMstProto.itemRepresenExt9Title', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt10Title', full_name='DicTypeMstProto.itemRepresenExt10Title', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt11Title', full_name='DicTypeMstProto.itemRepresenExt11Title', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt12Title', full_name='DicTypeMstProto.itemRepresenExt12Title', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt13Title', full_name='DicTypeMstProto.itemRepresenExt13Title', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt14Title', full_name='DicTypeMstProto.itemRepresenExt14Title', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt15Title', full_name='DicTypeMstProto.itemRepresenExt15Title', index=23,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt16Title', full_name='DicTypeMstProto.itemRepresenExt16Title', index=24,
      number=25, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt17Title', full_name='DicTypeMstProto.itemRepresenExt17Title', index=25,
      number=26, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt18Title', full_name='DicTypeMstProto.itemRepresenExt18Title', index=26,
      number=27, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt19Title', full_name='DicTypeMstProto.itemRepresenExt19Title', index=27,
      number=28, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='itemRepresenExt20Title', full_name='DicTypeMstProto.itemRepresenExt20Title', index=28,
      number=29, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=865,
)

DESCRIPTOR.message_types_by_name['DicTypeMstProto'] = _DICTYPEMSTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DicTypeMstProto = _reflection.GeneratedProtocolMessageType('DicTypeMstProto', (_message.Message,), {
  'DESCRIPTOR' : _DICTYPEMSTPROTO,
  '__module__' : 'DicTypeMstProto_pb2'
  # @@protoc_insertion_point(class_scope:DicTypeMstProto)
  })
_sym_db.RegisterMessage(DicTypeMstProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
