# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DigitalImageExamOutputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DigitalImageExamOutputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!DigitalImageExamOutputProto.proto\"a\n\x1b\x44igitalImageExamOutputProto\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x16\n\x0eorganizationID\x18\x02 \x01(\t\x12\x17\n\x0f\x61\x63\x63\x65ssionNumber\x18\x03 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_DIGITALIMAGEEXAMOUTPUTPROTO = _descriptor.Descriptor(
  name='DigitalImageExamOutputProto',
  full_name='DigitalImageExamOutputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='DigitalImageExamOutputProto.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='DigitalImageExamOutputProto.organizationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accessionNumber', full_name='DigitalImageExamOutputProto.accessionNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['DigitalImageExamOutputProto'] = _DIGITALIMAGEEXAMOUTPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DigitalImageExamOutputProto = _reflection.GeneratedProtocolMessageType('DigitalImageExamOutputProto', (_message.Message,), {
  'DESCRIPTOR' : _DIGITALIMAGEEXAMOUTPUTPROTO,
  '__module__' : 'DigitalImageExamOutputProto_pb2'
  # @@protoc_insertion_point(class_scope:DigitalImageExamOutputProto)
  })
_sym_db.RegisterMessage(DigitalImageExamOutputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
