# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DocStatusProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DocStatusProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x44ocStatusProto.proto\"t\n\x0e\x44ocStatusProto\x12\x18\n\x10\x65xamResultStatus\x18\x01 \x01(\x08\x12\x19\n\x11\x65xamWrittenStatus\x18\x02 \x01(\x08\x12\x16\n\x0e\x65xamFilmStatus\x18\x03 \x01(\x08\x12\x15\n\rexamImgStatus\x18\x04 \x01(\x08\x42\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_DOCSTATUSPROTO = _descriptor.Descriptor(
  name='DocStatusProto',
  full_name='DocStatusProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='examResultStatus', full_name='DocStatusProto.examResultStatus', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examWrittenStatus', full_name='DocStatusProto.examWrittenStatus', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examFilmStatus', full_name='DocStatusProto.examFilmStatus', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examImgStatus', full_name='DocStatusProto.examImgStatus', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['DocStatusProto'] = _DOCSTATUSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocStatusProto = _reflection.GeneratedProtocolMessageType('DocStatusProto', (_message.Message,), {
  'DESCRIPTOR' : _DOCSTATUSPROTO,
  '__module__' : 'DocStatusProto_pb2'
  # @@protoc_insertion_point(class_scope:DocStatusProto)
  })
_sym_db.RegisterMessage(DocStatusProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
