# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DocumentInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from compileProtobuf.dstPb.UserOrgInfoProto import Proto_pb2 as UserOrgInfoProto_dot_Proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DocumentInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x44ocumentInputProto.proto\x1a\x16UserOrgInfoProto.Proto\"\x94\x04\n\x12\x44ocumentInputProto\x12\x0f\n\x07\x65xamUID\x18\x01 \x01(\t\x12\x10\n\x08typeCode\x18\x02 \x01(\t\x12\x11\n\tclassCode\x18\x03 \x01(\t\x12\x14\n\x0c\x62usinessType\x18\x04 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_Token\x18\x05 \x01(\t\x12\x14\n\x0cshareAddress\x18\x06 \x01(\t\x12\x15\n\rshareUserName\x18\x07 \x01(\t\x12\x15\n\rsharePassWord\x18\x08 \x01(\t\x12\x10\n\x08pageSize\x18\t \x01(\x05\x12\x13\n\x0b\x63urrentPage\x18\n \x01(\x05\x12\r\n\x05token\x18\x0b \x01(\t\x12\x15\n\risInteragency\x18\x0c \x01(\t\x12\x19\n\x11isInteragencyExam\x18\r \x01(\t\x12\x1b\n\x13isInteragencyClinic\x18\x0e \x01(\t\x12\x1e\n\x16isInteragencyStatistic\x18\x0f \x01(\t\x12#\n\x08userInfo\x18\x10 \x01(\x0b\x32\x11.UserOrgInfoProto\x12\x19\n\x11isInteragencyData\x18\x11 \x01(\t\x12\x13\n\x0b\x61pplyMethod\x18\x12 \x01(\t\x12\x1a\n\x12isInterconnectData\x18\x13 \x01(\t\x12\x17\n\x0f\x61\x63\x63\x65ssionNumber\x18\x14 \x01(\t\x12\x16\n\x0eorganizationID\x18\x15 \x01(\t\x12\x11\n\texamToken\x18\x16 \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
  ,
  dependencies=[UserOrgInfoProto_dot_Proto__pb2.DESCRIPTOR,])




_DOCUMENTINPUTPROTO = _descriptor.Descriptor(
  name='DocumentInputProto',
  full_name='DocumentInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='examUID', full_name='DocumentInputProto.examUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typeCode', full_name='DocumentInputProto.typeCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classCode', full_name='DocumentInputProto.classCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='businessType', full_name='DocumentInputProto.businessType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_Token', full_name='DocumentInputProto.access_Token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shareAddress', full_name='DocumentInputProto.shareAddress', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shareUserName', full_name='DocumentInputProto.shareUserName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sharePassWord', full_name='DocumentInputProto.sharePassWord', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='DocumentInputProto.pageSize', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='DocumentInputProto.currentPage', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='DocumentInputProto.token', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragency', full_name='DocumentInputProto.isInteragency', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyExam', full_name='DocumentInputProto.isInteragencyExam', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyClinic', full_name='DocumentInputProto.isInteragencyClinic', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyStatistic', full_name='DocumentInputProto.isInteragencyStatistic', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='DocumentInputProto.userInfo', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyData', full_name='DocumentInputProto.isInteragencyData', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='applyMethod', full_name='DocumentInputProto.applyMethod', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInterconnectData', full_name='DocumentInputProto.isInterconnectData', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accessionNumber', full_name='DocumentInputProto.accessionNumber', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='DocumentInputProto.organizationID', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examToken', full_name='DocumentInputProto.examToken', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=585,
)

_DOCUMENTINPUTPROTO.fields_by_name['userInfo'].message_type = UserOrgInfoProto_dot_Proto__pb2._USERORGINFOPROTO
DESCRIPTOR.message_types_by_name['DocumentInputProto'] = _DOCUMENTINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocumentInputProto = _reflection.GeneratedProtocolMessageType('DocumentInputProto', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTINPUTPROTO,
  '__module__' : 'DocumentInputProto_pb2'
  # @@protoc_insertion_point(class_scope:DocumentInputProto)
  })
_sym_db.RegisterMessage(DocumentInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
