# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExamItemsInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from UserOrgInfoProto import Proto_pb2 as UserOrgInfoProto_dot_Proto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExamItemsInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x45xamItemsInputProto.proto\x1a\x16UserOrgInfoProto.Proto\"\xa3\x02\n\x13\x45xamItemsInputProto\x12\x10\n\x08visitUID\x18\x01 \x01(\t\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x13\n\x0b\x63urrentPage\x18\x03 \x01(\x05\x12\r\n\x05token\x18\x04 \x01(\t\x12\x15\n\risInteragency\x18\x05 \x01(\t\x12\x19\n\x11isInteragencyExam\x18\x06 \x01(\t\x12\x1b\n\x13isInteragencyClinic\x18\x07 \x01(\t\x12\x1e\n\x16isInteragencyStatistic\x18\x08 \x01(\t\x12#\n\x08userInfo\x18\t \x01(\x0b\x32\x11.UserOrgInfoProto\x12\x19\n\x11isInteragencyData\x18\n \x01(\t\x12\x15\n\rorgnizationID\x18\x0b \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
  ,
  dependencies=[UserOrgInfoProto_dot_Proto__pb2.DESCRIPTOR,])




_EXAMITEMSINPUTPROTO = _descriptor.Descriptor(
  name='ExamItemsInputProto',
  full_name='ExamItemsInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='visitUID', full_name='ExamItemsInputProto.visitUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='ExamItemsInputProto.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='ExamItemsInputProto.currentPage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='ExamItemsInputProto.token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragency', full_name='ExamItemsInputProto.isInteragency', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyExam', full_name='ExamItemsInputProto.isInteragencyExam', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyClinic', full_name='ExamItemsInputProto.isInteragencyClinic', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyStatistic', full_name='ExamItemsInputProto.isInteragencyStatistic', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userInfo', full_name='ExamItemsInputProto.userInfo', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isInteragencyData', full_name='ExamItemsInputProto.isInteragencyData', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orgnizationID', full_name='ExamItemsInputProto.orgnizationID', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=345,
)

_EXAMITEMSINPUTPROTO.fields_by_name['userInfo'].message_type = UserOrgInfoProto_dot_Proto__pb2._USERORGINFOPROTO
DESCRIPTOR.message_types_by_name['ExamItemsInputProto'] = _EXAMITEMSINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExamItemsInputProto = _reflection.GeneratedProtocolMessageType('ExamItemsInputProto', (_message.Message,), {
  'DESCRIPTOR' : _EXAMITEMSINPUTPROTO,
  '__module__' : 'ExamItemsInputProto_pb2'
  # @@protoc_insertion_point(class_scope:ExamItemsInputProto)
  })
_sym_db.RegisterMessage(ExamItemsInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
