# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetGainRecordListInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetGainRecordListInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!GetGainRecordListInputProto.proto\"x\n\x1bGetGainRecordListInputProto\x12\x13\n\x0b\x63urrentPage\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x16\n\x0eorganizationID\x18\x05 \x01(\t\"\x80\x01\n\x19GetGainRecordListOutProto\x12\x15\n\rgainRecordUID\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x12\n\ncreateTime\x18\x03 \x01(\t\x12\x18\n\x10organizationName\x18\x04 \x01(\t\x12\x10\n\x08typeName\x18\x05 \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
)




_GETGAINRECORDLISTINPUTPROTO = _descriptor.Descriptor(
  name='GetGainRecordListInputProto',
  full_name='GetGainRecordListInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='GetGainRecordListInputProto.currentPage', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='GetGainRecordListInputProto.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='GetGainRecordListInputProto.date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='GetGainRecordListInputProto.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='GetGainRecordListInputProto.organizationID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=157,
)


_GETGAINRECORDLISTOUTPROTO = _descriptor.Descriptor(
  name='GetGainRecordListOutProto',
  full_name='GetGainRecordListOutProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gainRecordUID', full_name='GetGainRecordListOutProto.gainRecordUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='GetGainRecordListOutProto.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='createTime', full_name='GetGainRecordListOutProto.createTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationName', full_name='GetGainRecordListOutProto.organizationName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typeName', full_name='GetGainRecordListOutProto.typeName', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=288,
)

DESCRIPTOR.message_types_by_name['GetGainRecordListInputProto'] = _GETGAINRECORDLISTINPUTPROTO
DESCRIPTOR.message_types_by_name['GetGainRecordListOutProto'] = _GETGAINRECORDLISTOUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetGainRecordListInputProto = _reflection.GeneratedProtocolMessageType('GetGainRecordListInputProto', (_message.Message,), {
  'DESCRIPTOR' : _GETGAINRECORDLISTINPUTPROTO,
  '__module__' : 'GetGainRecordListInputProto_pb2'
  # @@protoc_insertion_point(class_scope:GetGainRecordListInputProto)
  })
_sym_db.RegisterMessage(GetGainRecordListInputProto)

GetGainRecordListOutProto = _reflection.GeneratedProtocolMessageType('GetGainRecordListOutProto', (_message.Message,), {
  'DESCRIPTOR' : _GETGAINRECORDLISTOUTPROTO,
  '__module__' : 'GetGainRecordListInputProto_pb2'
  # @@protoc_insertion_point(class_scope:GetGainRecordListOutProto)
  })
_sym_db.RegisterMessage(GetGainRecordListOutProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
