# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetOperateRecordListInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetOperateRecordListInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$GetOperateRecordListInputProto.proto\"m\n\x1eGetOperateRecordListInputProto\x12\x16\n\x0eorganizationID\x18\x01 \x01(\t\x12\x13\n\x0b\x63urrentPage\x18\x02 \x01(\x05\x12\x10\n\x08pageSize\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
)




_GETOPERATERECORDLISTINPUTPROTO = _descriptor.Descriptor(
  name='GetOperateRecordListInputProto',
  full_name='GetOperateRecordListInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='GetOperateRecordListInputProto.organizationID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='GetOperateRecordListInputProto.currentPage', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='GetOperateRecordListInputProto.pageSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='GetOperateRecordListInputProto.date', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['GetOperateRecordListInputProto'] = _GETOPERATERECORDLISTINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOperateRecordListInputProto = _reflection.GeneratedProtocolMessageType('GetOperateRecordListInputProto', (_message.Message,), {
  'DESCRIPTOR' : _GETOPERATERECORDLISTINPUTPROTO,
  '__module__' : 'GetOperateRecordListInputProto_pb2'
  # @@protoc_insertion_point(class_scope:GetOperateRecordListInputProto)
  })
_sym_db.RegisterMessage(GetOperateRecordListInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
