# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetPatientInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetPatientInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aGetPatientInputProto.proto\"Z\n\x14GetPatientInputProto\x12\x17\n\x0f\x61\x63\x63\x65ssionNumber\x18\x01 \x01(\t\x12\x16\n\x0eorganizationID\x18\x02 \x01(\t\x12\x11\n\texamToken\x18\x03 \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
)




_GETPATIENTINPUTPROTO = _descriptor.Descriptor(
  name='GetPatientInputProto',
  full_name='GetPatientInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessionNumber', full_name='GetPatientInputProto.accessionNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='GetPatientInputProto.organizationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='examToken', full_name='GetPatientInputProto.examToken', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['GetPatientInputProto'] = _GETPATIENTINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPatientInputProto = _reflection.GeneratedProtocolMessageType('GetPatientInputProto', (_message.Message,), {
  'DESCRIPTOR' : _GETPATIENTINPUTPROTO,
  '__module__' : 'GetPatientInputProto_pb2'
  # @@protoc_insertion_point(class_scope:GetPatientInputProto)
  })
_sym_db.RegisterMessage(GetPatientInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
