# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrganizationDtoProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrganizationDtoProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aOrganizationDtoProto.proto\"n\n\x14OrganizationDtoProto\x12\x16\n\x0eorganizationID\x18\x01 \x01(\t\x12\x18\n\x10organizationName\x18\x02 \x01(\t\x12$\n\ndeptMstDto\x18\x03 \x03(\x0b\x32\x10.DeptMstDtoProto\"w\n\x0f\x44\x65ptMstDtoProto\x12\x16\n\x0eorganizationID\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65ptName\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65ptID\x18\x03 \x01(\t\x12\x18\n\x10organizationName\x18\x04 \x01(\t\x12\x10\n\x08\x64\x65ptType\x18\x05 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_ORGANIZATIONDTOPROTO = _descriptor.Descriptor(
  name='OrganizationDtoProto',
  full_name='OrganizationDtoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='OrganizationDtoProto.organizationID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationName', full_name='OrganizationDtoProto.organizationName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deptMstDto', full_name='OrganizationDtoProto.deptMstDto', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=140,
)


_DEPTMSTDTOPROTO = _descriptor.Descriptor(
  name='DeptMstDtoProto',
  full_name='DeptMstDtoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='DeptMstDtoProto.organizationID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deptName', full_name='DeptMstDtoProto.deptName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deptID', full_name='DeptMstDtoProto.deptID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationName', full_name='DeptMstDtoProto.organizationName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deptType', full_name='DeptMstDtoProto.deptType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=261,
)

_ORGANIZATIONDTOPROTO.fields_by_name['deptMstDto'].message_type = _DEPTMSTDTOPROTO
DESCRIPTOR.message_types_by_name['OrganizationDtoProto'] = _ORGANIZATIONDTOPROTO
DESCRIPTOR.message_types_by_name['DeptMstDtoProto'] = _DEPTMSTDTOPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrganizationDtoProto = _reflection.GeneratedProtocolMessageType('OrganizationDtoProto', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATIONDTOPROTO,
  '__module__' : 'OrganizationDtoProto_pb2'
  # @@protoc_insertion_point(class_scope:OrganizationDtoProto)
  })
_sym_db.RegisterMessage(OrganizationDtoProto)

DeptMstDtoProto = _reflection.GeneratedProtocolMessageType('DeptMstDtoProto', (_message.Message,), {
  'DESCRIPTOR' : _DEPTMSTDTOPROTO,
  '__module__' : 'OrganizationDtoProto_pb2'
  # @@protoc_insertion_point(class_scope:DeptMstDtoProto)
  })
_sym_db.RegisterMessage(DeptMstDtoProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
