# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organizationIDInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='organizationIDInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eorganizationIDInputProto.proto\"2\n\x18organizationIDInputProto\x12\x16\n\x0eorganizationID\x18\x01 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_ORGANIZATIONIDINPUTPROTO = _descriptor.Descriptor(
  name='organizationIDInputProto',
  full_name='organizationIDInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='organizationIDInputProto.organizationID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['organizationIDInputProto'] = _ORGANIZATIONIDINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

organizationIDInputProto = _reflection.GeneratedProtocolMessageType('organizationIDInputProto', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATIONIDINPUTPROTO,
  '__module__' : 'organizationIDInputProto_pb2'
  # @@protoc_insertion_point(class_scope:organizationIDInputProto)
  })
_sym_db.RegisterMessage(organizationIDInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
