# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrgInputProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrgInputProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13OrgInputProto.proto\"Y\n\rOrgInputProto\x12\x18\n\x10organizationName\x18\x01 \x01(\t\x12\x1c\n\x14searchOrganizationID\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65ptType\x18\x03 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_ORGINPUTPROTO = _descriptor.Descriptor(
  name='OrgInputProto',
  full_name='OrgInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organizationName', full_name='OrgInputProto.organizationName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='searchOrganizationID', full_name='OrgInputProto.searchOrganizationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deptType', full_name='OrgInputProto.deptType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['OrgInputProto'] = _ORGINPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrgInputProto = _reflection.GeneratedProtocolMessageType('OrgInputProto', (_message.Message,), {
  'DESCRIPTOR' : _ORGINPUTPROTO,
  '__module__' : 'OrgInputProto_pb2'
  # @@protoc_insertion_point(class_scope:OrgInputProto)
  })
_sym_db.RegisterMessage(OrgInputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
