# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ShareExamProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ShareExamProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ShareExamProto.proto\"n\n\x13ShareExamInputProto\x12\x17\n\x0f\x61\x63\x63\x65ssionNumber\x18\x01 \x01(\t\x12\x16\n\x0eorganizationID\x18\x02 \x01(\t\x12\x11\n\texpireMin\x18\x03 \x01(\x05\x12\x13\n\x0brelatedAuth\x18\x04 \x01(\x08\")\n\x14ShareExamOutputProto\x12\x11\n\texamToken\x18\x01 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_SHAREEXAMINPUTPROTO = _descriptor.Descriptor(
  name='ShareExamInputProto',
  full_name='ShareExamInputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accessionNumber', full_name='ShareExamInputProto.accessionNumber', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='organizationID', full_name='ShareExamInputProto.organizationID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expireMin', full_name='ShareExamInputProto.expireMin', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relatedAuth', full_name='ShareExamInputProto.relatedAuth', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=134,
)


_SHAREEXAMOUTPUTPROTO = _descriptor.Descriptor(
  name='ShareExamOutputProto',
  full_name='ShareExamOutputProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='examToken', full_name='ShareExamOutputProto.examToken', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['ShareExamInputProto'] = _SHAREEXAMINPUTPROTO
DESCRIPTOR.message_types_by_name['ShareExamOutputProto'] = _SHAREEXAMOUTPUTPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareExamInputProto = _reflection.GeneratedProtocolMessageType('ShareExamInputProto', (_message.Message,), {
  'DESCRIPTOR' : _SHAREEXAMINPUTPROTO,
  '__module__' : 'ShareExamProto_pb2'
  # @@protoc_insertion_point(class_scope:ShareExamInputProto)
  })
_sym_db.RegisterMessage(ShareExamInputProto)

ShareExamOutputProto = _reflection.GeneratedProtocolMessageType('ShareExamOutputProto', (_message.Message,), {
  'DESCRIPTOR' : _SHAREEXAMOUTPUTPROTO,
  '__module__' : 'ShareExamProto_pb2'
  # @@protoc_insertion_point(class_scope:ShareExamOutputProto)
  })
_sym_db.RegisterMessage(ShareExamOutputProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
