# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SystemInitProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SystemInitProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\027TomTaw.eWordIMCIS.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15SystemInitProto.proto\"\xbe\x01\n\x12ParamAppenderProto\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x1a\n\x12maxSizeRollBackups\x18\x02 \x01(\t\x12\x14\n\x0c\x61ppendToFile\x18\x03 \x01(\t\x12\x17\n\x0fmaximumFileSize\x18\x04 \x01(\t\x12\x15\n\rlayoutPattern\x18\x05 \x01(\t\x12\x14\n\x0crollingStyle\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x61tePattern\x18\x07 \x01(\t\x12\r\n\x05level\x18\x08 \x01(\t\"\xaa\x01\n\x10\x44\x42\x43onfigDtoProto\x12\x0e\n\x06\x64\x62Type\x18\x01 \x01(\t\x12\x0f\n\x07lsSlave\x18\x02 \x01(\t\x12\x12\n\ndataSource\x18\x03 \x01(\t\x12\x16\n\x0einitialCatalog\x18\x04 \x01(\t\x12\x0e\n\x06userId\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\x12\x10\n\x08hostPort\x18\x07 \x01(\t\x12\x15\n\rdbInstallType\x18\x08 \x01(\tB\x1a\xaa\x02\x17TomTaw.eWordIMCIS.Protob\x06proto3'
)




_PARAMAPPENDERPROTO = _descriptor.Descriptor(
  name='ParamAppenderProto',
  full_name='ParamAppenderProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file', full_name='ParamAppenderProto.file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxSizeRollBackups', full_name='ParamAppenderProto.maxSizeRollBackups', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appendToFile', full_name='ParamAppenderProto.appendToFile', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maximumFileSize', full_name='ParamAppenderProto.maximumFileSize', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='layoutPattern', full_name='ParamAppenderProto.layoutPattern', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rollingStyle', full_name='ParamAppenderProto.rollingStyle', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datePattern', full_name='ParamAppenderProto.datePattern', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='ParamAppenderProto.level', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=216,
)


_DBCONFIGDTOPROTO = _descriptor.Descriptor(
  name='DBConfigDtoProto',
  full_name='DBConfigDtoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dbType', full_name='DBConfigDtoProto.dbType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lsSlave', full_name='DBConfigDtoProto.lsSlave', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataSource', full_name='DBConfigDtoProto.dataSource', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initialCatalog', full_name='DBConfigDtoProto.initialCatalog', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userId', full_name='DBConfigDtoProto.userId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='DBConfigDtoProto.password', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hostPort', full_name='DBConfigDtoProto.hostPort', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dbInstallType', full_name='DBConfigDtoProto.dbInstallType', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=389,
)

DESCRIPTOR.message_types_by_name['ParamAppenderProto'] = _PARAMAPPENDERPROTO
DESCRIPTOR.message_types_by_name['DBConfigDtoProto'] = _DBCONFIGDTOPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParamAppenderProto = _reflection.GeneratedProtocolMessageType('ParamAppenderProto', (_message.Message,), {
  'DESCRIPTOR' : _PARAMAPPENDERPROTO,
  '__module__' : 'SystemInitProto_pb2'
  # @@protoc_insertion_point(class_scope:ParamAppenderProto)
  })
_sym_db.RegisterMessage(ParamAppenderProto)

DBConfigDtoProto = _reflection.GeneratedProtocolMessageType('DBConfigDtoProto', (_message.Message,), {
  'DESCRIPTOR' : _DBCONFIGDTOPROTO,
  '__module__' : 'SystemInitProto_pb2'
  # @@protoc_insertion_point(class_scope:DBConfigDtoProto)
  })
_sym_db.RegisterMessage(DBConfigDtoProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
