# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkloadPlusDtoProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WorkloadDtoProto_pb2 as WorkloadDtoProto__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorkloadPlusDtoProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aWorkloadPlusDtoProto.proto\x1a\x16WorkloadDtoProto.proto\"\x9d\x02\n\x14WorkloadPlusDtoProto\x12&\n\x0bworkloadDto\x18\x01 \x03(\x0b\x32\x11.WorkloadDtoProto\x12\x10\n\x08row1Name\x18\x02 \x01(\t\x12\x10\n\x08row2Name\x18\x03 \x01(\t\x12\x13\n\x0b\x63olumn1Name\x18\x04 \x01(\t\x12\x13\n\x0b\x63olumn2Name\x18\x05 \x01(\t\x12\x17\n\x0frow1DisplayName\x18\x06 \x01(\t\x12\x17\n\x0frow2DisplayName\x18\x07 \x01(\t\x12\x1a\n\x12\x63olumn1DisplayName\x18\x08 \x01(\t\x12\x1a\n\x12\x63olumn2DisplayName\x18\t \x01(\t\x12\x10\n\x08rowTotal\x18\n \x01(\x05\x12\x13\n\x0b\x63olumnTotal\x18\x0b \x01(\x05\x42\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
  ,
  dependencies=[WorkloadDtoProto__pb2.DESCRIPTOR,])




_WORKLOADPLUSDTOPROTO = _descriptor.Descriptor(
  name='WorkloadPlusDtoProto',
  full_name='WorkloadPlusDtoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='workloadDto', full_name='WorkloadPlusDtoProto.workloadDto', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row1Name', full_name='WorkloadPlusDtoProto.row1Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row2Name', full_name='WorkloadPlusDtoProto.row2Name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column1Name', full_name='WorkloadPlusDtoProto.column1Name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column2Name', full_name='WorkloadPlusDtoProto.column2Name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row1DisplayName', full_name='WorkloadPlusDtoProto.row1DisplayName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row2DisplayName', full_name='WorkloadPlusDtoProto.row2DisplayName', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column1DisplayName', full_name='WorkloadPlusDtoProto.column1DisplayName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column2DisplayName', full_name='WorkloadPlusDtoProto.column2DisplayName', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rowTotal', full_name='WorkloadPlusDtoProto.rowTotal', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columnTotal', full_name='WorkloadPlusDtoProto.columnTotal', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=340,
)

_WORKLOADPLUSDTOPROTO.fields_by_name['workloadDto'].message_type = WorkloadDtoProto__pb2._WORKLOADDTOPROTO
DESCRIPTOR.message_types_by_name['WorkloadPlusDtoProto'] = _WORKLOADPLUSDTOPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkloadPlusDtoProto = _reflection.GeneratedProtocolMessageType('WorkloadPlusDtoProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOADPLUSDTOPROTO,
  '__module__' : 'WorkloadPlusDtoProto_pb2'
  # @@protoc_insertion_point(class_scope:WorkloadPlusDtoProto)
  })
_sym_db.RegisterMessage(WorkloadPlusDtoProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
