# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WorkloadDtoProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WorkloadDtoProto.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\037TomTaw.eWordIMCIS.WebAPI.Models',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16WorkloadDtoProto.proto\"_\n\x10WorkloadDtoProto\x12\r\n\x05\x63ount\x18\x01 \x01(\t\x12\x0c\n\x04row1\x18\x02 \x01(\t\x12\x0c\n\x04row2\x18\x03 \x01(\t\x12\x0f\n\x07\x63olumn1\x18\x04 \x01(\t\x12\x0f\n\x07\x63olumn2\x18\x05 \x01(\tB\"\xaa\x02\x1fTomTaw.eWordIMCIS.WebAPI.Modelsb\x06proto3'
)




_WORKLOADDTOPROTO = _descriptor.Descriptor(
  name='WorkloadDtoProto',
  full_name='WorkloadDtoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='WorkloadDtoProto.count', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row1', full_name='WorkloadDtoProto.row1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='row2', full_name='WorkloadDtoProto.row2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column1', full_name='WorkloadDtoProto.column1', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column2', full_name='WorkloadDtoProto.column2', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['WorkloadDtoProto'] = _WORKLOADDTOPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkloadDtoProto = _reflection.GeneratedProtocolMessageType('WorkloadDtoProto', (_message.Message,), {
  'DESCRIPTOR' : _WORKLOADDTOPROTO,
  '__module__' : 'WorkloadDtoProto_pb2'
  # @@protoc_insertion_point(class_scope:WorkloadDtoProto)
  })
_sym_db.RegisterMessage(WorkloadDtoProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
